version: '3.8'
services:
  redis:
    image: redis
    expose: 
    - 6379
    volumes:
      - ./redis_data:/data
  tm:
    build: .
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl --fail http://localhost:3000 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - redis
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379"